#pragma once

#include <windows.h>
#include <mmdeviceapi.h>
#include <audioclient.h>

#ifndef KSAUDIO_SPEAKER_2POINT1
#define KSAUDIO_SPEAKER_2POINT1 (KSAUDIO_SPEAKER_STEREO | SPEAKER_LOW_FREQUENCY)
#endif
#define KSAUDIO_SPEAKER_2POINT1 (KSAUDIO_SPEAKER_STEREO | SPEAKER_LOW_FREQUENCY)
#define KSAUDIO_SPEAKER_3POINT0 (KSAUDIO_SPEAKER_STEREO | SPEAKER_FRONT_CENTER)
#define KSAUDIO_SPEAKER_3POINT1 \
	(KSAUDIO_SPEAKER_STEREO | SPEAKER_FRONT_CENTER | SPEAKER_LOW_FREQUENCY)
#define KSAUDIO_SPEAKER_5POINT0_BACK \
	(KSAUDIO_SPEAKER_3POINT0 | SPEAKER_BACK_LEFT | SPEAKER_BACK_RIGHT)
#define KSAUDIO_SPEAKER_4POINT1 (KSAUDIO_SPEAKER_QUAD | SPEAKER_LOW_FREQUENCY)
#define KSAUDIO_SPEAKER_6POINT0                                             \
	(KSAUDIO_SPEAKER_3POINT0 | SPEAKER_SIDE_LEFT | SPEAKER_SIDE_RIGHT | \
	 SPEAKER_BACK_CENTER)
#define KSAUDIO_SPEAKER_6POINT1_BACK                                        \
	(KSAUDIO_SPEAKER_3POINT0 | SPEAKER_BACK_LEFT | SPEAKER_BACK_RIGHT | \
	 SPEAKER_BACK_CENTER | SPEAKER_LOW_FREQUENCY)
#define KSAUDIO_SPEAKER_7POINT0 \
	(KSAUDIO_SPEAKER_5POINT0_BACK | SPEAKER_SIDE_LEFT | SPEAKER_BACK_RIGHT)
#define KSAUDIO_SPEAKER_OCTAGONAL                                          \
	(KSAUDIO_SPEAKER_QUAD | SPEAKER_FRONT_CENTER | SPEAKER_SIDE_LEFT | \
	 SPEAKER_SIDE_RIGHT | SPEAKER_BACK_CENTER)
#define KSAUDIO_SPEAKER_9POINT0 (KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_TOP_CENTER)
#define KSAUDIO_SPEAKER_10POINT0                                    \
	(KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_FRONT_LEFT_OF_CENTER | \
	 SPEAKER_FRONT_RIGHT_OF_CENTER)
#define KSAUDIO_SPEAKER_11POINT0                                    \
	(KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_FRONT_LEFT_OF_CENTER | \
	 SPEAKER_FRONT_RIGHT_OF_CENTER | SPEAKER_TOP_CENTER)
#define KSAUDIO_SPEAKER_12POINT0                                    \
	(KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_FRONT_LEFT_OF_CENTER | \
	 SPEAKER_FRONT_RIGHT_OF_CENTER | SPEAKER_TOP_FRONT_LEFT |   \
	 SPEAKER_TOP_FRONT_RIGHT)
#define KSAUDIO_SPEAKER_13POINT0                              \
	(KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_TOP_FRONT_LEFT | \
	 SPEAKER_TOP_FRONT_CENTER | SPEAKER_TOP_FRONT_RIGHT | \
	 SPEAKER_TOP_CENTER | SPEAKER_TOP_BACK_CENTER)
#define KSAUDIO_SPEAKER_14POINT0                              \
	(KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_TOP_FRONT_LEFT | \
	 SPEAKER_TOP_FRONT_CENTER | SPEAKER_TOP_FRONT_RIGHT | \
	 SPEAKER_TOP_CENTER | SPEAKER_TOP_BACK_LEFT | SPEAKER_TOP_BACK_RIGHT)
#define KSAUDIO_SPEAKER_15POINT0                                               \
	(KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_TOP_FRONT_LEFT |                  \
	 SPEAKER_TOP_FRONT_CENTER | SPEAKER_TOP_FRONT_RIGHT |                  \
	 SPEAKER_TOP_CENTER | SPEAKER_TOP_BACK_LEFT | SPEAKER_TOP_BACK_RIGHT | \
	 SPEAKER_TOP_BACK_CENTER)
#define KSAUDIO_SPEAKER_HEXADECAGONAL                               \
	(KSAUDIO_SPEAKER_OCTAGONAL | SPEAKER_FRONT_LEFT_OF_CENTER | \
	 SPEAKER_FRONT_RIGHT_OF_CENTER | SPEAKER_TOP_BACK_LEFT |    \
	 SPEAKER_TOP_BACK_RIGHT | SPEAKER_TOP_BACK_CENTER |         \
	 SPEAKER_TOP_FRONT_LEFT | SPEAKER_TOP_FRONT_RIGHT |         \
	 SPEAKER_TOP_FRONT_CENTER)
// the windows API can't define 22.2; there's not enough speakers; so use this instead ...
#define KSAUDIO_SPEAKER_NHK SPEAKER_RESERVED

#define safe_release(ptr)                          \
	do {                                       \
		if (ptr) {                         \
			ptr->lpVtbl->Release(ptr); \
		}                                  \
	} while (false)
